UserParameter=postfix.process.running,/usr/bin/pgrep -fAc /usr/lib/postfix/sbin/master
UserParameter=postfix.pfmailq,/usr/local/bin/postfix_zabbix.sh pfmailq
UserParameter=postfix.connections,sh -c "ss -tn state established '( dport = :25 or sport = :25 )' 2>/dev/null | tail -n +2 | wc -l"
#UserParameter=postfix.fetch_log_data
UserParameter=postfix.queue.disk,df --output=pcent /var/spool/postfix | tail -n 1 | sed 's/%//' | awk '{$1=$1};1'
UserParameter=postfix.version,/usr/sbin/postconf mail_version | awk '{print $3}'
UserParameter=postfix.submission.check,/usr/local/bin/postfix_zabbix.sh submission_check
UserParameter=postfix.submissions.check,/usr/local/bin/postfix_zabbix.sh submissions_check
UserParameter=postfix.smtp.check,/usr/local/bin/postfix_zabbix.sh smtp_check
UserParameter=postfix.tls.cert.raw.465,/usr/local/bin/postfix_zabbix.sh cert_raw_465
UserParameter=postfix.tls.cert.raw.587,/usr/local/bin/postfix_zabbix.sh cert_raw_587
UserParameter=postfix.tls.cert.days.465,/usr/local/bin/postfix_zabbix.sh cert_days_465
UserParameter=postfix.tls.cert.days.587,/usr/local/bin/postfix_zabbix.sh cert_days_587
UserParameter=postfix.log.errors,/usr/local/bin/postfix_zabbix.sh errors
UserParameter=postfix.log.warnings,/usr/local/bin/postfix_zabbix.sh warnings
UserParameter=postfix.log.sasl_auth_failed,/usr/local/bin/postfix_zabbix.sh sasl_auth_failed
UserParameter=postfix.log.relay_denied,/usr/local/bin/postfix_zabbix.sh relay_denied
UserParameter=postfix.log.spam_rejected,/usr/local/bin/postfix_zabbix.sh spam_rejected
UserParameter=postfix.log.rbl_reject,/usr/local/bin/postfix_zabbix.sh rbl_reject
UserParameter=postfix.log.user_unknown,/usr/local/bin/postfix_zabbix.sh user_unknown
UserParameter=postfix.log.connection_timeout,/usr/local/bin/postfix_zabbix.sh connection_timeout
UserParameter=postfix.log.quota_exceeded,/usr/local/bin/postfix_zabbix.sh quota_exceeded
UserParameter=postfix.log.tls_failed,/usr/local/bin/postfix_zabbix.sh tls_failed
UserParameter=postfix.log.virus_found,/usr/local/bin/postfix_zabbix.sh virus_found
UserParameter=postfix.postscreen.active,/usr/local/bin/postfix_zabbix.sh postscreen_active
UserParameter=postfix.postscreen.pass_new,/usr/local/bin/postfix_zabbix.sh postscreen_pass_new
UserParameter=postfix.postscreen.pass_old,/usr/local/bin/postfix_zabbix.sh postscreen_pass_old
UserParameter=postfix.postscreen.reject,/usr/local/bin/postfix_zabbix.sh postscreen_reject
UserParameter=postfix.postscreen.dnsbl,/usr/local/bin/postfix_zabbix.sh postscreen_dnsbl
UserParameter=postfix.postscreen.pregreet,/usr/local/bin/postfix_zabbix.sh postscreen_pregreet
UserParameter=postfix.postscreen.hangup,/usr/local/bin/postfix_zabbix.sh postsreen_hangup
UserParameter=postfix.postscreen.whitelisted,/usr/local/bin/postfix_zabbix.sh postscreen_whitelisted
UserParameter=postfix.postscreen.connect,/usr/local/bin/postfix_zabbix.sh postscreen_connect
UserParameter=postfix.emails.received,/usr/local/bin/postfix_zabbix.sh received
UserParameter=postfix.emails.delivered,/usr/local/bin/postfix_zabbix.sh delivered
UserParameter=postfix.emails.bounced,/usr/local/bin/postfix_zabbix.sh bounced
UserParameter=postfix.emails.deferred,/usr/local/bin/postfix_zabbix.sh deferred
UserParameter=postfix.emails.rejected,/usr/local/bin/postfix_zabbix.sh rejected
UserParameter=postfix.emails.reject_warnings,/usr/local/bin/postfix_zabbix.sh reject_warnings
UserParameter=postfix.emails.discarded,/usr/local/bin/postfix_zabbix.sh discarded
UserParameter=postfix.emails.held,/usr/local/bin/postfix_zabbix.sh held
UserParameter=postfix.emails.forwarded,/usr/local/bin/postfix_zabbix.sh forwarded
UserParameter=postfix.bytes_received,/usr/local/bin/postfix_zabbix.sh bytes_received
UserParameter=postfix.bytes_delivered,/usr/local/bin/postfix_zabbix.sh bytes_delivered
UserParameter=postfix.senders,/usr/local/bin/postfix_zabbix.sh senders
UserParameter=postfix.recipients,/usr/local/bin/postfix_zabbix.sh recipients
